### ISSUE TITLE
Is it mandatory to use MQTT over Websocket on Charge point device or Just Websocket is sufficient?

### ISSUE THREAD

**Issue by Bhuvi-Naveen** [aws-samples/aws-ocpp-gateway#40]
Dear @galinsky ,

Thanks to confirm if it is mandatory to use MQTT over Websockets on Charge point device? 

OR

The communication between Charge point device and OCPP gateway can be based on Websockets and OCPP gateway internally uses MQTT communication with its internal services. 

Regards,
Bhuvi-Naveen

**Comment by galinsky** [comment]
If I understood your question, it’s the latter: charge point device to the gateway uses the OCPP protocol over WebSockets, while the gateway to the backend service(s) uses MQTT.

**Comment by Bhuvi-Naveen** [comment]
Hi @galinsky,

Thank you for your response!

I have one more question, could you please let me know if OCPP Gateway code used in the proposed solution is developed by Amazon or it is third party stack? Also is it possible to host our own OCPP gateway code in the proposed solution instead of AWS provided OCPP Gateway? please advise.

Regards,
Bhuvi-Naveen

**Comment by galinsky** [comment]
@Bhuvi-Naveen the OCPP Gateway code included here was developed by Amazon. It takes dependencies on third-party libraries, specifically the `ocpp` python library used in `message_processor.py`. If your question is around using your own gateway solution instead of the `ocpp-gateway-container` code, that would surely be something you are free to do. You can also freely modify the `gateway.py` code to your own business needs.

**Comment by Bhuvi-Naveen** [comment]
Thanks Garry for the confirmation.

Regards,
Bhuvi-Naveen
